### ISSUE TITLE
Communication from NextJS to Main process

### ISSUE THREAD

**Issue by Jonovono** [kirill-konshin/next-electron-rsc#5]
This is really cool, crazy it works!

I am wondering how you would go about communicating from the NextJS views back to the main process? Would you follow the same preload, ipc approach?

**Comment by kirill-konshin** [comment]
You don't need to do anything special here. Next.js streams HTML/JS back to main via same HTTP mock. Just use native Next.js communication methods like route handlers and server side functions/components.

**Comment by gavan1** [comment]
@kirill-konshin Love what you've done! I've see this dones with IPC and the preload script. It's still not clear how to use you're lib to communicate with say the electron browser window.

**Comment by kirill-konshin** [comment]
You don't need IPC or preload script. You should communicate with Electron APIs from Server Components. Please read the article from readme: https://medium.com/@kirill.konshin/the-ultimate-electron-app-with-next-js-and-react-server-components-a5c0cabda72b

**Comment by kirill-konshin** [comment]
You can add whatever Electron API here https://github.com/kirill-konshin/next-electron-rsc/blob/main/demo/src/app/test/route.ts

Or here https://github.com/kirill-konshin/next-electron-rsc/blob/main/demo/src/app/page.tsx#L4

**Comment by kirill-konshin** [comment]
Feel free to make a small PR with some Electron API call there.

**Comment by gavan1** [comment]
I am really going back and using your repo to get the basics up and running.
Following your doc and steps thing just don't run , hence I cleaned up tooling and used pnpm, removing workspace references.

I'de suggest you actually testing the repo and following those steps, if you are using yarn I'de recommend locking that depency.

As is, it is not possible to git clone and follow our you're documented steps to get the demo working.

**Comment by gavan1** [comment]
@Jonovono how did you even get this repo working? Could you update the docs?
